package duong.thuy.parking.entities;
// Generated Apr 12, 2020 6:47:23 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Parking generated by hbm2java
 */
@Entity
@Table(name = "parking", catalog = "baido")
public class Parking implements java.io.Serializable {

	private Long id;
	private String parkingName;
	private String properties;
	private Date createdAt;
	private Date modifiedAt;
	private Date deletedAt;
	private String address;
	private String kindOf;
	private String parkingImage;
	private String payment;
	private String status;
	private String longitude;
	private String latitude;
	private String capacity;
	private String blockAmount;
	private Long ownerId;
	private String certificateOfLand;

	public Parking() {
	}

	public Parking(String parkingName, String properties, Date createdAt, Date modifiedAt, Date deletedAt,
			String address, String kindOf, String parkingImage, String payment, String status, String longitude,
			String latitude, String capacity, String blockAmount, Long ownerId, String certificateOfLand) {
		this.parkingName = parkingName;
		this.properties = properties;
		this.createdAt = createdAt;
		this.modifiedAt = modifiedAt;
		this.deletedAt = deletedAt;
		this.address = address;
		this.kindOf = kindOf;
		this.parkingImage = parkingImage;
		this.payment = payment;
		this.status = status;
		this.longitude = longitude;
		this.latitude = latitude;
		this.capacity = capacity;
		this.blockAmount = blockAmount;
		this.ownerId = ownerId;
		this.certificateOfLand = certificateOfLand;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "parking_name", nullable = false, length = 65535)
	public String getParkingName() {
		return this.parkingName;
	}

	public void setParkingName(String parkingName) {
		this.parkingName = parkingName;
	}

	@Column(name = "properties", nullable = false, length = 65535)
	public String getProperties() {
		return this.properties;
	}

	public void setProperties(String properties) {
		this.properties = properties;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_at", nullable = false, length = 10)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modified_at", nullable = false, length = 10)
	public Date getModifiedAt() {
		return this.modifiedAt;
	}

	public void setModifiedAt(Date modifiedAt) {
		this.modifiedAt = modifiedAt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "deleted_at", nullable = false, length = 10)
	public Date getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Date deletedAt) {
		this.deletedAt = deletedAt;
	}

	@Column(name = "address", nullable = false, length = 65535)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "kind_of", nullable = false, length = 65535)
	public String getKindOf() {
		return this.kindOf;
	}

	public void setKindOf(String kindOf) {
		this.kindOf = kindOf;
	}

	@Column(name = "parking_image", nullable = false, length = 65535)
	public String getParkingImage() {
		return this.parkingImage;
	}

	public void setParkingImage(String parkingImage) {
		this.parkingImage = parkingImage;
	}

	@Column(name = "payment", nullable = false, length = 65535)
	public String getPayment() {
		return this.payment;
	}

	public void setPayment(String payment) {
		this.payment = payment;
	}

	@Column(name = "status", nullable = false, length = 65535)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "longitude", nullable = false, length = 65535)
	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	@Column(name = "latitude", nullable = false, length = 65535)
	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	@Column(name = "capacity", nullable = false, length = 65535)
	public String getCapacity() {
		return this.capacity;
	}

	public void setCapacity(String capacity) {
		this.capacity = capacity;
	}

	@Column(name = "block_amount", nullable = false, length = 65535)
	public String getBlockAmount() {
		return this.blockAmount;
	}

	public void setBlockAmount(String blockAmount) {
		this.blockAmount = blockAmount;
	}

	@Column(name = "owner_id", nullable = false)
	public Long getOwnerId() {
		return this.ownerId;
	}

	public void setOwnerId(Long ownerId) {
		this.ownerId = ownerId;
	}

	@Column(name = "certificate_of_land", nullable = false, length = 65535)
	public String getCertificateOfLand() {
		return this.certificateOfLand;
	}

	public void setCertificateOfLand(String certificateOfLand) {
		this.certificateOfLand = certificateOfLand;
	}

}
