package duong.thuy.parking.entities;
// Generated Apr 12, 2020 6:47:23 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transactions generated by hbm2java
 */
@Entity
@Table(name = "transactions", catalog = "baido")
public class Transactions implements java.io.Serializable {

	private Long id;
	private Long credentialId;
	private int parkingId;
	private Date createdAt;
	private String status;
	private Date sesion;
	private String amount;
	private Date modifiedAt;
	private String liencePlate;
	private Date startTime;
	private Date endTime;
	private String reasonMesage;

	public Transactions() {
	}

	public Transactions(Long credentialId, int parkingId, Date createdAt, String status, Date sesion, String amount,
			Date modifiedAt, String liencePlate, Date startTime, Date endTime, String reasonMesage) {
		this.credentialId = credentialId;
		this.parkingId = parkingId;
		this.createdAt = createdAt;
		this.status = status;
		this.sesion = sesion;
		this.amount = amount;
		this.modifiedAt = modifiedAt;
		this.liencePlate = liencePlate;
		this.startTime = startTime;
		this.endTime = endTime;
		this.reasonMesage = reasonMesage;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "credential_id", nullable = false)
	public Long getCredentialId() {
		return this.credentialId;
	}

	public void setCredentialId(Long credentialId) {
		this.credentialId = credentialId;
	}

	@Column(name = "parking_id", nullable = false)
	public int getParkingId() {
		return this.parkingId;
	}

	public void setParkingId(int parkingId) {
		this.parkingId = parkingId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_at", nullable = false, length = 10)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "status", nullable = false, length = 65535)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "sesion", nullable = false, length = 8)
	public Date getSesion() {
		return this.sesion;
	}

	public void setSesion(Date sesion) {
		this.sesion = sesion;
	}

	@Column(name = "amount", nullable = false, length = 65535)
	public String getAmount() {
		return this.amount;
	}

	public void setAmount(String amount) {
		this.amount = amount;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modified_at", nullable = false, length = 10)
	public Date getModifiedAt() {
		return this.modifiedAt;
	}

	public void setModifiedAt(Date modifiedAt) {
		this.modifiedAt = modifiedAt;
	}

	@Column(name = "lience_plate", nullable = false, length = 65535)
	public String getLiencePlate() {
		return this.liencePlate;
	}

	public void setLiencePlate(String liencePlate) {
		this.liencePlate = liencePlate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_time", nullable = false, length = 19)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_time", nullable = false, length = 19)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Column(name = "reason_mesage", nullable = false, length = 65535)
	public String getReasonMesage() {
		return this.reasonMesage;
	}

	public void setReasonMesage(String reasonMesage) {
		this.reasonMesage = reasonMesage;
	}

}
