package duong.thuy.parking.entities;
// Generated Apr 12, 2020 6:47:23 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Userdevices generated by hbm2java
 */
@Entity
@Table(name = "userdevices", catalog = "baido")
public class UserDevices implements java.io.Serializable {

	private Long id;
	private String deviceToken;
	private Integer credentialId;

	public UserDevices() {
	}

	public UserDevices(String deviceToken, Integer credentialId) {
		this.deviceToken = deviceToken;
		this.credentialId = credentialId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "device_token", length = 65535)
	public String getDeviceToken() {
		return this.deviceToken;
	}

	public void setDeviceToken(String deviceToken) {
		this.deviceToken = deviceToken;
	}

	@Column(name = "credential_id")
	public Integer getCredentialId() {
		return this.credentialId;
	}

	public void setCredentialId(Integer credentialId) {
		this.credentialId = credentialId;
	}

}
